# for container-y goodness:
sudo: false

language: python

python:
  - "2.7"

# command to install dependencies
install:
- "pip install -U pip setuptools"
- "pip install -Ur requirements.txt"

# command to run tests, e.g. python setup.py test
script:
- nosetests --with-cov --cov=xlrd
- python setup.py sdist
- python setup.py bdist_wheel --universal

deploy:
  provider: script
  script: bash dist_gemfury.sh
  on:
    tags: true
