dist: xenial
sudo: false
cache: pip

language: python

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36

install:
  - pip install tox

script:
  - tox
  - python setup.py sdist
  - python setup.py bdist_wheel --universal

after_success:
  - if [ $TOXENV != lint ]; then pip install coveralls; fi
  - if [ $TOXENV != lint ]; then coveralls; fi

deploy:
  provider: script
  script: bash dist_gemfury.sh
  skip_cleanup: true
  on:
    tags: true
